/* GENERATED by scripts/manifesto/build.py -- do not edit by hand.
   Re-run that script to remeasure the alpha-mask exports.

   One record per word, because words are the atomic layout unit: they wrap
   whole or not at all, so a line break can never split letters.

   Coordinates are in a shared unit space where the body x-height is
   10 units. The browser crops the original PNG alpha; there are
   no reconstructed paths and CSS supplies the visible ink colour.

     x, y  crop origin in the source mask, in units
     w, h  bounding box of the ink, in units
     b     baseline offset from the top of that box. Aligning words by b (not
           by box top) is what lets them sit on one straight line despite
           different ascenders and descenders.
     n     optical baseline nudge for source-specific irregularities.
     m     authored i-dot/period crops used for optical weight correction. */

export type ManifestoMark = {
  /** Position inside the word crop. */
  x: number;
  y: number;
  w: number;
  h: number;
  /** Mask position for this crop inside the full source sprite. */
  mx: number;
  my: number;
};

export type ManifestoWord = {
  /** The word itself -- also the accessible text. */
  t: string;
  /** Source line, 0 = title. Line breaks are not reused for layout. */
  l: number;
  /** Which original alpha-mask PNG this word is cropped from. */
  s: "title" | "body";
  x: number;
  y: number;
  w: number;
  h: number;
  b: number;
  /** Optical baseline correction in normalized handwriting units. */
  n: number;
  /** Authored i-dots and periods that receive extra optical weight. */
  m: ManifestoMark[];
};

/** Median word space in the original hand, in units. */
export const WORD_SPACE = 9.3;

/** Body x-height in units; the unit scale everything else is relative to. */
export const X_HEIGHT = 10;

/** Full source-mask dimensions in the same normalized unit space. */
export const MANIFESTO_SOURCES = {
  title: { w: 391.3, h: 521.8 },
  body: { w: 387.0, h: 560.7 },
} as const;

/** Build-time measurements used to match the two authored body exports. */
export const MANIFESTO_BODY_NORMALIZATION = {
  part1XHeight: 41.74,
  part2XHeightBefore: 48.78,
  part2Scale: 0.85582,
  part2XHeightAfter: 41.74,
  lineStep: 112.85,
} as const;

export const MANIFESTO_WORDS: ManifestoWord[] = [
  { t: "Design", l: 0, s: "title", x: 13.8, y: 30.4, w: 108.7, h: 48.8, b: 38.9, n: 0.0, m: [{ x: 73.7, y: 19.1, w: 3.4, h: 3.4, mx: -87.4, my: -49.5 }] },
  { t: "Manifesto", l: 0, s: "title", x: 137.7, y: 32.1, w: 147.1, h: 39.1, b: 34.1, n: 0.0, m: [{ x: 74.4, y: 13.5, w: 4.6, h: 3.6, mx: -212.1, my: -45.7 }] },
  { t: "I", l: 1, s: "body", x: 10.6, y: 12.1, w: 22.0, h: 17.4, b: 15.7, n: 0.0, m: [] },
  { t: "decided", l: 1, s: "body", x: 43.7, y: 8.9, w: 72.5, h: 20.3, b: 17.9, n: 0.0, m: [{ x: 30.4, y: 0.5, w: 2.9, h: 2.7, mx: -74.2, my: -9.4 }] },
  { t: "to", l: 1, s: "body", x: 123.2, y: 11.1, w: 23.7, h: 17.2, b: 15.4, n: 0.0, m: [] },
  { t: "use", l: 1, s: "body", x: 158.7, y: 11.8, w: 31.9, h: 14.3, b: 12.8, n: 0.0, m: [] },
  { t: "this", l: 1, s: "body", x: 191.3, y: 10.4, w: 43.7, h: 16.7, b: 14.0, n: 0.0, m: [{ x: 28.3, y: 0.5, w: 2.9, h: 3.4, mx: -219.6, my: -10.9 }] },
  { t: "space", l: 1, s: "body", x: 241.8, y: 13.0, w: 55.1, h: 18.6, b: 12.6, n: 0.0, m: [] },
  { t: "to", l: 1, s: "body", x: 301.0, y: 10.1, w: 24.4, h: 15.5, b: 13.6, n: 0.0, m: [] },
  { t: "share", l: 2, s: "body", x: 10.6, y: 40.1, w: 51.5, h: 16.7, b: 13.3, n: 0.0, m: [] },
  { t: "my", l: 2, s: "body", x: 71.3, y: 40.1, w: 26.8, h: 20.0, b: 16.4, n: 0.0, m: [] },
  { t: "thoughts", l: 2, s: "body", x: 102.4, y: 37.4, w: 80.9, h: 22.9, b: 15.5, n: 0.0, m: [] },
  { t: "on", l: 2, s: "body", x: 189.6, y: 41.5, w: 23.4, h: 11.8, b: 10.4, n: 0.0, m: [] },
  { t: "AI.", l: 2, s: "body", x: 225.1, y: 36.2, w: 37.2, h: 18.8, b: 17.4, n: 0.0, m: [{ x: 34.1, y: 14.0, w: 2.9, h: 3.1, mx: -259.2, my: -50.2 }] },
  { t: "AI", l: 2, s: "body", x: 269.1, y: 36.0, w: 27.3, h: 18.4, b: 16.3, n: 0.0, m: [] },
  { t: "can", l: 2, s: "body", x: 303.9, y: 39.6, w: 33.8, h: 12.3, b: 10.9, n: 0.0, m: [] },
  { t: "write", l: 3, s: "body", x: 10.6, y: 65.7, w: 51.9, h: 17.4, b: 15.0, n: 0.0, m: [{ x: 25.6, y: 0.5, w: 2.4, h: 2.7, mx: -36.2, my: -66.2 }] },
  { t: "like", l: 3, s: "body", x: 71.7, y: 67.6, w: 35.0, h: 17.4, b: 14.7, n: 0.0, m: [{ x: 6.5, y: 0.5, w: 2.4, h: 2.4, mx: -78.3, my: -68.1 }] },
  { t: "us,", l: 3, s: "body", x: 110.4, y: 71.0, w: 29.2, h: 15.0, b: 10.9, n: 0.0, m: [] },
  { t: "talk", l: 3, s: "body", x: 146.4, y: 68.6, w: 43.0, h: 14.3, b: 12.3, n: 0.0, m: [] },
  { t: "like", l: 3, s: "body", x: 194.5, y: 66.4, w: 37.0, h: 15.9, b: 14.3, n: 0.0, m: [{ x: 7.0, y: 0.5, w: 2.7, h: 2.4, mx: -201.5, my: -66.9 }] },
  { t: "us,", l: 3, s: "body", x: 238.7, y: 69.3, w: 28.3, h: 13.8, b: 9.9, n: 0.0, m: [] },
  { t: "and", l: 3, s: "body", x: 269.8, y: 65.0, w: 32.9, h: 15.7, b: 14.0, n: 0.0, m: [] },
  { t: "imitate", l: 3, s: "body", x: 307.3, y: 63.8, w: 62.1, h: 16.9, b: 14.3, n: 0.0, m: [{ x: 1.4, y: 1.7, w: 2.7, h: 2.2, mx: -308.7, my: -65.5 }, { x: 18.6, y: 0.5, w: 2.7, h: 2.7, mx: -325.9, my: -64.3 }] },
  { t: "everything", l: 4, s: "body", x: 10.6, y: 93.0, w: 93.2, h: 20.3, b: 17.4, n: 0.0, m: [{ x: 61.4, y: 0.5, w: 2.7, h: 2.4, mx: -72.0, my: -93.5 }] },
  { t: "that", l: 4, s: "body", x: 113.8, y: 96.6, w: 42.5, h: 14.5, b: 11.4, n: 0.0, m: [] },
  { t: "we", l: 4, s: "body", x: 164.3, y: 97.1, w: 28.0, h: 12.8, b: 11.1, n: 0.0, m: [] },
  { t: "do.", l: 4, s: "body", x: 200.3, y: 95.2, w: 30.2, h: 14.5, b: 12.8, n: 0.0, m: [{ x: 25.6, y: 9.4, w: 4.3, h: 3.4, mx: -225.9, my: -104.6 }] },
  { t: "At", l: 4, s: "body", x: 237.5, y: 93.7, w: 22.5, h: 16.4, b: 13.3, n: 0.0, m: [] },
  { t: "this", l: 4, s: "body", x: 263.8, y: 93.2, w: 38.9, h: 15.2, b: 13.3, n: 0.0, m: [{ x: 25.4, y: 0.5, w: 2.4, h: 2.4, mx: -289.1, my: -93.7 }] },
  { t: "point,", l: 4, s: "body", x: 316.2, y: 93.5, w: 49.5, h: 19.1, b: 13.8, n: 0.0, m: [{ x: 20.0, y: 0.5, w: 2.9, h: 2.2, mx: -336.3, my: -94.0 }] },
  { t: "I", l: 5, s: "body", x: 10.6, y: 124.2, w: 19.1, h: 13.3, b: 11.4, n: 0.0, m: [] },
  { t: "don't", l: 5, s: "body", x: 43.2, y: 122.5, w: 45.7, h: 14.5, b: 12.8, n: 0.0, m: [] },
  { t: "know", l: 5, s: "body", x: 99.8, y: 123.4, w: 44.9, h: 13.8, b: 11.1, n: 0.0, m: [] },
  { t: "where", l: 5, s: "body", x: 155.3, y: 122.0, w: 52.9, h: 14.7, b: 13.0, n: 0.0, m: [] },
  { t: "a", l: 5, s: "body", x: 220.3, y: 123.2, w: 14.7, h: 10.9, b: 9.4, n: 0.0, m: [] },
  { t: "person", l: 5, s: "body", x: 245.7, y: 121.3, w: 57.7, h: 18.1, b: 11.6, n: 0.0, m: [] },
  { t: "ends", l: 5, s: "body", x: 313.3, y: 119.1, w: 39.9, h: 14.7, b: 13.3, n: 0.0, m: [] },
  { t: "and", l: 6, s: "body", x: 10.6, y: 148.8, w: 32.9, h: 16.4, b: 14.5, n: 0.0, m: [] },
  { t: "where", l: 6, s: "body", x: 71.5, y: 421.5, w: 51.9, h: 13.5, b: 11.6, n: 0.0, m: [] },
  { t: "AI", l: 6, s: "body", x: 54.1, y: 149.0, w: 30.0, h: 15.2, b: 13.3, n: 0.0, m: [] },
  { t: "begins.", l: 6, s: "body", x: 93.0, y: 148.6, w: 66.2, h: 18.1, b: 13.5, n: 0.0, m: [{ x: 32.6, y: 1.4, w: 2.7, h: 2.7, mx: -125.6, my: -150.0 }, { x: 62.8, y: 10.9, w: 3.1, h: 3.1, mx: -155.8, my: -159.4 }] },
  { t: "But", l: 6, s: "body", x: 168.4, y: 148.8, w: 34.3, h: 16.4, b: 14.7, n: 0.0, m: [] },
  { t: "we", l: 6, s: "body", x: 210.9, y: 151.2, w: 24.9, h: 12.1, b: 10.4, n: 0.0, m: [] },
  { t: "are", l: 6, s: "body", x: 246.1, y: 151.0, w: 31.6, h: 12.1, b: 10.6, n: 0.0, m: [] },
  { t: "humans.", l: 6, s: "body", x: 285.0, y: 147.1, w: 64.7, h: 15.2, b: 13.0, n: 0.0, m: [{ x: 61.4, y: 9.7, w: 3.1, h: 3.1, mx: -346.4, my: -156.8 }] },
  { t: "We", l: 7, s: "body", x: 10.6, y: 178.5, w: 29.2, h: 12.6, b: 11.2, n: 0.0, m: [] },
  { t: "are", l: 7, s: "body", x: 47.8, y: 180.0, w: 33.3, h: 12.6, b: 11.1, n: 0.0, m: [] },
  { t: "made", l: 7, s: "body", x: 94.4, y: 178.0, w: 48.3, h: 15.2, b: 13.5, n: 0.0, m: [] },
  { t: "of", l: 7, s: "body", x: 152.9, y: 179.5, w: 20.8, h: 12.6, b: 11.1, n: 0.0, m: [] },
  { t: "flesh", l: 7, s: "body", x: 182.1, y: 178.3, w: 46.9, h: 13.8, b: 10.9, n: 0.0, m: [] },
  { t: "and", l: 7, s: "body", x: 237.2, y: 175.6, w: 32.9, h: 13.8, b: 12.1, n: 0.0, m: [] },
  { t: "blood.", l: 7, s: "body", x: 277.3, y: 174.4, w: 50.5, h: 15.7, b: 13.3, n: 0.0, m: [{ x: 46.6, y: 10.1, w: 3.6, h: 3.6, mx: -323.9, my: -184.6 }] },
  { t: "we", l: 7, s: "body", x: 332.4, y: 175.6, w: 27.8, h: 13.8, b: 12.3, n: 0.0, m: [] },
  { t: "create,", l: 8, s: "body", x: 10.6, y: 204.1, w: 63.0, h: 15.2, b: 13.2, n: 0.0, m: [] },
  { t: "we", l: 8, s: "body", x: 79.0, y: 205.8, w: 25.6, h: 12.3, b: 10.9, n: 0.0, m: [] },
  { t: "dance,", l: 8, s: "body", x: 118.1, y: 204.1, w: 59.7, h: 15.0, b: 13.0, n: 0.0, m: [] },
  { t: "and", l: 8, s: "body", x: 181.7, y: 204.8, w: 34.1, h: 14.3, b: 12.1, n: 0.0, m: [] },
  { t: "make", l: 8, s: "body", x: 225.6, y: 204.6, w: 45.9, h: 13.5, b: 11.4, n: 0.0, m: [] },
  { t: "art.", l: 8, s: "body", x: 280.0, y: 202.4, w: 36.5, h: 13.3, b: 11.8, n: 0.0, m: [{ x: 33.8, y: 9.9, w: 2.4, h: 2.4, mx: -313.8, my: -212.3 }] },
  { t: "So", l: 8, s: "body", x: 328.0, y: 199.5, w: 17.9, h: 15.0, b: 13.5, n: 0.0, m: [] },
  { t: "let's", l: 9, s: "body", x: 10.6, y: 234.6, w: 41.8, h: 15.9, b: 13.8, n: 0.0, m: [] },
  { t: "not", l: 9, s: "body", x: 59.2, y: 234.1, w: 26.3, h: 14.3, b: 11.8, n: 0.0, m: [] },
  { t: "see", l: 9, s: "body", x: 93.7, y: 233.6, w: 30.9, h: 13.3, b: 11.6, n: 0.0, m: [] },
  { t: "this", l: 9, s: "body", x: 137.7, y: 230.9, w: 37.2, h: 15.2, b: 12.1, n: 0.0, m: [{ x: 22.5, y: 0.5, w: 2.7, h: 2.7, mx: -160.2, my: -231.4 }] },
  { t: "as", l: 9, s: "body", x: 186.2, y: 231.4, w: 21.7, h: 12.1, b: 10.4, n: 0.0, m: [] },
  { t: "AI", l: 9, s: "body", x: 216.4, y: 230.2, w: 28.7, h: 14.7, b: 12.6, n: 0.0, m: [] },
  { t: "is", l: 9, s: "body", x: 254.1, y: 231.2, w: 15.7, h: 12.6, b: 11.1, n: 0.0, m: [{ x: 0.7, y: 0.5, w: 2.9, h: 3.1, mx: -254.8, my: -231.7 }] },
  { t: "taking", l: 9, s: "body", x: 277.6, y: 229.5, w: 54.4, h: 17.9, b: 10.9, n: 0.0, m: [{ x: 30.2, y: 0.5, w: 2.7, h: 2.2, mx: -307.7, my: -230.0 }] },
  { t: "over", l: 9, s: "body", x: 338.9, y: 230.0, w: 37.4, h: 11.8, b: 10.4, n: 0.0, m: [] },
  { t: "our", l: 10, s: "body", x: 10.6, y: 263.3, w: 27.5, h: 13.0, b: 11.4, n: 0.0, m: [] },
  { t: "lives,", l: 10, s: "body", x: 48.3, y: 260.2, w: 48.3, h: 15.7, b: 12.6, n: 0.0, m: [{ x: 8.5, y: 0.5, w: 2.2, h: 2.4, mx: -56.8, my: -260.6 }] },
  { t: "but", l: 10, s: "body", x: 101.7, y: 260.2, w: 34.8, h: 14.7, b: 13.3, n: 0.0, m: [] },
  { t: "that", l: 10, s: "body", x: 145.7, y: 259.4, w: 40.6, h: 14.0, b: 10.9, n: 0.0, m: [] },
  { t: "AI", l: 10, s: "body", x: 197.4, y: 256.8, w: 25.1, h: 13.8, b: 12.3, n: 0.0, m: [] },
  { t: "is", l: 10, s: "body", x: 232.6, y: 256.8, w: 17.2, h: 14.0, b: 12.6, n: 0.0, m: [{ x: 1.9, y: 0.5, w: 2.9, h: 2.7, mx: -234.6, my: -257.3 }] },
  { t: "letting", l: 10, s: "body", x: 261.1, y: 254.6, w: 55.6, h: 20.0, b: 12.8, n: 0.0, m: [{ x: 28.3, y: 0.5, w: 2.2, h: 2.4, mx: -289.4, my: -255.1 }] },
  { t: "us", l: 10, s: "body", x: 330.5, y: 257.5, w: 19.3, h: 11.8, b: 10.4, n: 0.0, m: [] },
  { t: "have", l: 11, s: "body", x: 10.6, y: 288.9, w: 43.5, h: 14.7, b: 11.8, n: 0.0, m: [] },
  { t: "more", l: 11, s: "body", x: 65.2, y: 289.4, w: 45.7, h: 12.3, b: 10.4, n: 0.0, m: [] },
  { t: "life", l: 11, s: "body", x: 124.6, y: 284.3, w: 35.0, h: 16.7, b: 14.3, n: 0.0, m: [{ x: 5.8, y: 0.5, w: 2.9, h: 2.7, mx: -130.4, my: -284.8 }] },
  { t: "to", l: 11, s: "body", x: 169.6, y: 287.0, w: 20.5, h: 12.1, b: 10.6, n: 0.0, m: [] },
  { t: "live.", l: 11, s: "body", x: 198.3, y: 284.3, w: 37.0, h: 14.0, b: 12.3, n: 0.0, m: [{ x: 6.0, y: 0.5, w: 2.7, h: 2.9, mx: -204.4, my: -284.8 }, { x: 34.3, y: 8.0, w: 2.4, h: 2.4, mx: -232.6, my: -292.3 }] },
  { t: "We", l: 11, s: "body", x: 242.5, y: 285.8, w: 31.6, h: 15.0, b: 13.4, n: 0.0, m: [] },
  { t: "can", l: 11, s: "body", x: 280.2, y: 286.0, w: 30.4, h: 13.0, b: 11.2, n: 0.0, m: [] },
  { t: "take", l: 11, s: "body", x: 318.4, y: 283.3, w: 45.4, h: 13.5, b: 11.6, n: 0.0, m: [] },
  { t: "back", l: 12, s: "body", x: 10.6, y: 315.5, w: 45.7, h: 14.7, b: 12.3, n: 0.0, m: [] },
  { t: "control", l: 12, s: "body", x: 67.4, y: 313.3, w: 55.1, h: 15.7, b: 13.8, n: 0.0, m: [] },
  { t: "in", l: 12, s: "body", x: 133.1, y: 312.6, w: 20.5, h: 14.0, b: 12.3, n: 0.0, m: [{ x: 0.7, y: 0.5, w: 2.9, h: 2.7, mx: -133.8, my: -313.1 }] },
  { t: "the", l: 12, s: "body", x: 166.2, y: 312.6, w: 33.8, h: 14.3, b: 12.8, n: 0.0, m: [] },
  { t: "creative", l: 12, s: "body", x: 211.6, y: 310.6, w: 72.0, h: 16.9, b: 14.5, n: 0.0, m: [{ x: 47.3, y: 0.5, w: 2.4, h: 2.7, mx: -259.0, my: -311.1 }] },
  { t: "process.", l: 12, s: "body", x: 294.9, y: 313.5, w: 68.6, h: 17.4, b: 11.6, n: 0.0, m: [{ x: 65.9, y: 7.2, w: 2.4, h: 2.7, mx: -360.9, my: -320.8 }] },
  { t: "Automate", l: 13, s: "body", x: 10.4, y: 337.2, w: 81.2, h: 18.1, b: 15.0, n: 0.0, m: [] },
  { t: "what", l: 13, s: "body", x: 99.3, y: 339.4, w: 45.2, h: 14.5, b: 12.6, n: 0.0, m: [] },
  { t: "we", l: 13, s: "body", x: 152.2, y: 341.8, w: 26.8, h: 12.1, b: 10.6, n: 0.0, m: [] },
  { t: "need", l: 13, s: "body", x: 184.8, y: 338.2, w: 43.2, h: 15.9, b: 14.0, n: 0.0, m: [] },
  { t: "and", l: 13, s: "body", x: 235.8, y: 339.2, w: 34.8, h: 15.7, b: 14.0, n: 0.0, m: [] },
  { t: "make", l: 14, s: "body", x: 10.4, y: 367.7, w: 46.6, h: 13.0, b: 11.1, n: 0.0, m: [] },
  { t: "more", l: 14, s: "body", x: 66.7, y: 369.8, w: 44.7, h: 11.8, b: 10.1, n: 0.0, m: [] },
  { t: "time", l: 14, s: "body", x: 117.2, y: 367.4, w: 45.9, h: 14.3, b: 12.6, n: 0.0, m: [{ x: 11.6, y: 0.5, w: 3.1, h: 3.1, mx: -128.8, my: -367.9 }] },
  { t: "for", l: 14, s: "body", x: 169.8, y: 369.1, w: 29.5, h: 11.8, b: 10.4, n: 0.0, m: [] },
  { t: "the", l: 14, s: "body", x: 209.4, y: 368.1, w: 35.5, h: 14.0, b: 12.3, n: 0.0, m: [] },
  { t: "things", l: 14, s: "body", x: 248.6, y: 367.4, w: 56.5, h: 21.3, b: 13.3, n: 0.0, m: [{ x: 24.4, y: 0.5, w: 3.1, h: 2.7, mx: -273.0, my: -367.9 }] },
  { t: "that", l: 15, s: "body", x: 10.4, y: 393.0, w: 43.7, h: 15.2, b: 13.0, n: 0.0, m: [] },
  { t: "spark", l: 15, s: "body", x: 65.5, y: 394.0, w: 48.6, h: 19.1, b: 13.0, n: 0.0, m: [] },
  { t: "us", l: 15, s: "body", x: 124.4, y: 395.0, w: 21.0, h: 11.1, b: 9.9, n: 0.0, m: [] },
  { t: "joy.", l: 15, s: "body", x: 155.6, y: 391.8, w: 31.6, h: 23.4, b: 17.6, n: 0.0, m: [{ x: 28.0, y: 10.9, w: 3.4, h: 2.7, mx: -183.6, my: -402.7 }] },
  { t: "If", l: 15, s: "body", x: 196.1, y: 395.9, w: 23.9, h: 14.5, b: 12.8, n: 0.0, m: [] },
  { t: "we", l: 15, s: "body", x: 228.8, y: 397.4, w: 22.9, h: 12.1, b: 10.6, n: 0.0, m: [] },
  { t: "can", l: 15, s: "body", x: 261.9, y: 398.1, w: 28.5, h: 12.6, b: 10.9, n: 0.0, m: [] },
  { t: "learn", l: 16, s: "body", x: 10.4, y: 422.5, w: 50.2, h: 13.0, b: 11.4, n: 0.0, m: [] },
  { t: "where", l: 16, s: "body", x: 71.5, y: 421.5, w: 51.9, h: 13.5, b: 11.6, n: 0.0, m: [] },
  { t: "and", l: 16, s: "body", x: 132.6, y: 421.3, w: 30.7, h: 13.5, b: 11.8, n: 0.0, m: [] },
  { t: "when", l: 16, s: "body", x: 172.2, y: 421.5, w: 43.2, h: 14.7, b: 12.6, n: 0.0, m: [] },
  { t: "to", l: 16, s: "body", x: 221.8, y: 424.9, w: 21.3, h: 12.6, b: 10.6, n: 0.0, m: [] },
  { t: "use", l: 16, s: "body", x: 251.2, y: 422.7, w: 28.7, h: 13.3, b: 11.1, n: 0.0, m: [] },
  { t: "AI,", l: 16, s: "body", x: 287.9, y: 419.3, w: 29.7, h: 18.1, b: 14.7, n: 0.0, m: [] },
  { t: "we", l: 17, s: "body", x: 10.4, y: 452.0, w: 30.2, h: 12.6, b: 9.9, n: 0.0, m: [] },
  { t: "can", l: 17, s: "body", x: 50.2, y: 451.0, w: 30.4, h: 13.3, b: 11.4, n: 0.0, m: [] },
  { t: "bring", l: 17, s: "body", x: 89.6, y: 448.6, w: 42.3, h: 19.3, b: 12.8, n: 0.0, m: [{ x: 19.3, y: 0.5, w: 1.9, h: 2.2, mx: -108.9, my: -449.1 }] },
  { t: "our", l: 17, s: "body", x: 142.8, y: 449.1, w: 33.1, h: 14.3, b: 12.6, n: 0.0, m: [] },
  { t: "lives", l: 17, s: "body", x: 189.4, y: 448.8, w: 37.9, h: 15.0, b: 13.0, n: 0.0, m: [{ x: 7.2, y: 0.5, w: 2.9, h: 3.1, mx: -196.6, my: -449.3 }] },
  { t: "back", l: 17, s: "body", x: 239.1, y: 451.2, w: 41.5, h: 12.6, b: 10.9, n: 0.0, m: [] },
  { t: "to", l: 17, s: "body", x: 293.3, y: 449.1, w: 17.4, h: 14.5, b: 12.7, n: 0.0, m: [] },
  { t: "the", l: 18, s: "body", x: 10.4, y: 476.4, w: 34.5, h: 13.5, b: 12.1, n: 0.0, m: [] },
  { t: "art.", l: 18, s: "body", x: 54.6, y: 477.8, w: 34.3, h: 12.3, b: 10.6, n: 0.0, m: [{ x: 31.6, y: 8.7, w: 2.4, h: 2.2, mx: -86.2, my: -486.5 }] },
  { t: "We", l: 18, s: "body", x: 101.2, y: 476.6, w: 28.5, h: 13.0, b: 11.4, n: 0.0, m: [] },
  { t: "are", l: 18, s: "body", x: 135.5, y: 477.6, w: 30.4, h: 12.3, b: 10.6, n: 0.0, m: [] },
  { t: "a", l: 18, s: "body", x: 175.9, y: 479.3, w: 13.8, h: 12.3, b: 10.9, n: 0.0, m: [] },
  { t: "house", l: 18, s: "body", x: 196.4, y: 476.8, w: 47.6, h: 14.5, b: 11.4, n: 0.0, m: [] },
  { t: "for", l: 18, s: "body", x: 250.7, y: 478.3, w: 31.6, h: 13.5, b: 12.1, n: 0.0, m: [] },
  { t: "creative", l: 19, s: "body", x: 10.4, y: 502.9, w: 71.7, h: 15.7, b: 13.5, n: 0.0, m: [{ x: 45.9, y: 0.5, w: 2.4, h: 3.4, mx: -56.3, my: -503.4 }] },
  { t: "spirit.", l: 19, s: "body", x: 92.0, y: 500.5, w: 51.0, h: 20.3, b: 15.7, n: 0.0, m: [{ x: 16.2, y: 1.0, w: 3.4, h: 3.4, mx: -108.2, my: -501.5 }, { x: 33.6, y: 0.5, w: 2.9, h: 3.1, mx: -125.6, my: -501.0 }, { x: 47.3, y: 12.3, w: 3.4, h: 3.1, mx: -139.4, my: -512.8 }] },
  { t: "So", l: 19, s: "body", x: 154.4, y: 503.2, w: 19.3, h: 14.0, b: 12.6, n: 0.0, m: [] },
  { t: "let's", l: 19, s: "body", x: 189.4, y: 503.2, w: 39.6, h: 16.9, b: 14.5, n: 0.0, m: [] },
  { t: "be", l: 19, s: "body", x: 242.3, y: 503.2, w: 22.7, h: 14.0, b: 12.6, n: 0.0, m: [] },
  { t: "intentional", l: 20, s: "body", x: 10.4, y: 530.2, w: 91.1, h: 16.9, b: 13.3, n: 0.0, m: [{ x: 1.0, y: 1.2, w: 2.4, h: 2.4, mx: -11.4, my: -531.4 }, { x: 51.5, y: 0.5, w: 3.4, h: 3.6, mx: -61.8, my: -530.7 }] },
  { t: "about", l: 20, s: "body", x: 110.4, y: 530.9, w: 53.9, h: 14.3, b: 12.1, n: 0.0, m: [] },
  { t: "how", l: 20, s: "body", x: 180.7, y: 530.7, w: 33.3, h: 14.5, b: 12.6, n: 0.0, m: [] },
  { t: "we", l: 20, s: "body", x: 223.7, y: 530.7, w: 29.7, h: 12.8, b: 11.1, n: 0.0, m: [] },
  { t: "create.", l: 20, s: "body", x: 259.4, y: 528.8, w: 60.9, h: 14.7, b: 12.3, n: 0.0, m: [{ x: 57.2, y: 7.7, w: 3.4, h: 3.4, mx: -316.7, my: -536.5 }] },
];
